"""initial schema

Revision ID: f16977355ffe
Revises: 
Create Date: 2026-04-15 12:36:15.033355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16977355ffe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=False),
    sa.Column('medical_condition', sa.String(length=100), nullable=False),
    sa.Column('date_of_admission', sa.String(length=20), nullable=True),
    sa.Column('doctor', sa.String(length=100), nullable=True),
    sa.Column('hospital', sa.String(length=200), nullable=True),
    sa.Column('insurance_provider', sa.String(length=100), nullable=False),
    sa.Column('billing_amount', sa.Float(), nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=True),
    sa.Column('admission_type', sa.String(length=50), nullable=False),
    sa.Column('discharge_date', sa.String(length=20), nullable=True),
    sa.Column('medication', sa.String(length=100), nullable=False),
    sa.Column('test_result', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('medical_condition', sa.String(length=100), nullable=True),
    sa.Column('billing_amount', sa.Float(), nullable=True),
    sa.Column('admission_type', sa.String(length=50), nullable=True),
    sa.Column('insurance_provider', sa.String(length=100), nullable=True),
    sa.Column('medication', sa.String(length=100), nullable=True),
    sa.Column('predicted_result', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
